platform :ios, '12.1'

source 'https://github.com/CocoaPods/Specs.git'

target 'Granola' do
  platform :ios, '12.1'

  pod "Havrefras", :path => "../"

  pod 'Specta', '~> 1.0'
  pod 'Expecta', '~> 1.0'
  pod 'VVJSONSchemaValidation', '~> 1.3'
end
